### ISSUE TITLE
[PREGUNTA]

### ISSUE THREAD

**Issue by neoacevedo** [mercadopago/card-payment-sample-php#1]
Se envía un token de acuerdo a como veo el js pero, ¿de dónde sale ese token?

**Comment by andreagostinho-meli** [comment]
Hola @neoacevedo! Disculpe el retraso 
Creo que está hablando de esa línea, no?
https://github.com/mercadopago/card-payment-sample-php/blob/main/client/js/index.js#L68

Ese token es generado automáticamente por Mercado Pago SDK para que la información de la tarjeta sea enviada a los servidores de modo seguro.

**Comment by hdlopez** [comment]
buenas @neoacevedo ! Gracias por contactar con nosotros. Simplemente me gustaría aclarar que este canal es para issues o problemas con el código del ejemplo.

Para otro tipo de aportes o consultas sobre el ejemplo podemos usar el espacio de discussions.
